### ISSUE TITLE
head, head_prob = fbp.detect(img) error

### ISSUE THREAD

**Issue by panovr** [yassersouri/fast-bird-part-localization#3]
after running "head, head_prob = fbp.detect(img)", I have got these errors:

head, head_prob = fbp.detect(img)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fast_bird_part_localization/detector.py", line 23, in detect
    pred_box = geometry_utils.find_rect_from_preds(geometry_utils.post_process_preds(preds_img))
  File "fast_bird_part_localization/geometry_utils.py", line 205, in post_process_preds
    preds = skimage.morphology.closing(preds, skimage.morphology.square(10))
  File "/usr/lib/python2.7/dist-packages/skimage/morphology/grey.py", line 215, in closing
    dilated = dilation(image, selem)
  File "/usr/lib/python2.7/dist-packages/skimage/morphology/grey.py", line 112, in dilation
    image = img_as_ubyte(image)
  File "/usr/lib/python2.7/dist-packages/skimage/util/dtype.py", line 358, in img_as_ubyte
    return convert(image, np.uint8, force_copy)
  File "/usr/lib/python2.7/dist-packages/skimage/util/dtype.py", line 99, in convert
    raise ValueError("can not convert %s to %s." % (dtypeobj_in, dtypeobj))
ValueError: can not convert int64 to uint8.

**Comment by panovr** [comment]
after upgrade scikit-image to version '0.12.3', these errors are resolved.

However, there is another error:

head, head_prob = fbp.detect(img)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fast_bird_part_localization/detector.py", line 23, in detect
    pred_box = geometry_utils.find_rect_from_preds(geometry_utils.post_process_preds(preds_img))
  File "fast_bird_part_localization/geometry_utils.py", line 205, in post_process_preds
    preds = skimage.morphology.closing(preds, skimage.morphology.square(10))
AttributeError: 'module' object has no attribute 'morphology'

**Comment by panovr** [comment]
after running "head, head_prob = fbp.detect(img)"
/usr/local/lib/python2.7/dist-packages/skimage/morphology/misc.py:122: UserWarning: Only one label was provided to `remove_small_objects`. Did you mean to use a boolean array?
  warn("Only one label was provided to `remove_small_objects`. "

The head_prob is right displayed, but the image is without head bounding box showed.
